# Generated by Django 3.1.3 on 2021-02-12 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mydesign.models


class Migration(migrations.Migration):

    dependencies = [
        ('mydesign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDesignDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(blank=True, null=True, upload_to=mydesign.models.get_mydesign_design_path, validators=[django.core.validators.FileExtensionValidator(['ai', 'pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mydesign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='mydesign.mydesign')),
            ],
        ),
    ]
