# Generated by Django 2.2.1 on 2020-04-10 15:27

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='extra_info',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='producttag',
            name='extra_info',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='productusecase',
            name='extra_info',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
