# Generated by Django 2.2.1 on 2020-05-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200410_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-position']},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='position',
            field=models.PositiveSmallIntegerField(default=10000),
        ),
    ]
