# Generated by Django 2.2.1 on 2020-06-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200526_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['position']},
        ),
    ]
