# Generated by Django 2.2.1 on 2020-06-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200601_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_params',
        ),
    ]
