# Generated by Django 2.2.1 on 2020-06-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200611_1629'),
        ('products', '0005_remove_product_price_params'),
    ]

    operations = [
    ]
