# Generated by Django 2.2.1 on 2020-08-14 15:18

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('icon', models.FileField(blank=True, null=True, upload_to=products.models.get_product_category_tags_icon_image_path)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
