# Generated by Django 2.2.1 on 2020-08-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productcategorytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.ProductCategoryTag'),
        ),
    ]
