# Generated by Django 2.2.1 on 2020-08-26 15:40

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productcategory_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategorytag',
            name='icon',
        ),
        migrations.AddField(
            model_name='productcategorytag',
            name='extra_info',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
