# Generated by Django 2.2.1 on 2020-08-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200826_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorytag',
            name='position',
            field=models.PositiveSmallIntegerField(default=10000),
        ),
    ]
