# Generated by Django 2.2.1 on 2020-09-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productcategorytag_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorytag',
            options={'ordering': ['position']},
        ),
    ]
