# Generated by Django 2.2.1 on 2020-10-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_reorderable',
            field=models.BooleanField(default=True),
        ),
    ]
