# Generated by Django 2.2.1 on 2020-11-27 14:11

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201019_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['product', 'position']},
        ),
        migrations.AddField(
            model_name='productoption',
            name='modal_blocks',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
