# Generated by Django 2.2.1 on 2020-11-27 14:50

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201127_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_option_image_path),
        ),
    ]
