# Generated by Django 2.2.1 on 2020-11-27 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productoption_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptioncondition',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductOption'),
        ),
    ]
