# Generated by Django 2.2.1 on 2020-12-15 18:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productoptioncondition_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('pdf_height', models.PositiveIntegerField(default=0)),
                ('pdf_width', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('image_width', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='easydrafts', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='EasyDraftPrintArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('area_id', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(upload_to=products.models.get_easydraft_area_image_path)),
                ('is_printable', models.BooleanField(default=True)),
                ('image_pos_start_x', models.IntegerField(blank=True, default=0, null=True)),
                ('image_pos_start_y', models.IntegerField(blank=True, default=0, null=True)),
                ('image_pos_end_x', models.IntegerField(blank=True, default=0, null=True)),
                ('image_pos_end_y', models.IntegerField(blank=True, default=0, null=True)),
                ('pdf_pos_start_x', models.IntegerField(blank=True, default=0, null=True)),
                ('pdf_pos_start_y', models.IntegerField(blank=True, default=0, null=True)),
                ('pdf_pos_end_x', models.IntegerField(blank=True, default=0, null=True)),
                ('pdf_pos_end_y', models.IntegerField(blank=True, default=0, null=True)),
                ('easydraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printareas', to='products.EasyDraft')),
            ],
        ),
    ]
