# Generated by Django 2.2.1 on 2020-12-15 18:50

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201215_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easydraft',
            name='slug',
            field=models.SlugField(max_length=120, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
