# Generated by Django 2.2.1 on 2020-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20201215_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
