# Generated by Django 3.1.3 on 2021-01-13 17:00

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20201222_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easydraft',
            name='slug',
            field=models.SlugField(max_length=120, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
