# Generated by Django 3.1.3 on 2021-03-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210113_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='sample_unit_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
