# Generated by Django 3.1.3 on 2021-03-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20210302_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='sample_lot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
