# Generated by Django 3.1.3 on 2021-06-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_productprice_sample_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_custom_product',
            field=models.BooleanField(default=False),
        ),
    ]
