# Generated by Django 3.1.3 on 2022-03-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_is_custom_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='contact_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
