# Generated by Django 3.1.3 on 2023-02-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productinfo_contact_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='can_order_on_site',
            field=models.BooleanField(default=False),
        ),
    ]
