# Generated by Django 3.1.3 on 2023-03-06 16:14

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_productinfo_can_order_on_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExampleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.get_product_example_image_path)),
                ('example_url', models.URLField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_images', to='products.product')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
