# Generated by Django 3.1.3 on 2021-05-12 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import notices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20210331_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('icon_path', models.FileField(blank=True, null=True, upload_to=notices.models.get_notice_category_icon_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])])),
                ('post_attachable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NoticePost',
            fields=[
                ('notice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notices.notice')),
                ('post_title', models.CharField(default='canalからのお知らせ', max_length=120)),
                ('text', models.TextField()),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('notices.notice',),
        ),
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.notice')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notices.noticecategory'),
        ),
        migrations.AddField(
            model_name='notice',
            name='users',
            field=models.ManyToManyField(through='notices.NoticeRead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NoticeReminder',
            fields=[
                ('notice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notices.notice')),
                ('orderitem', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
            ],
            bases=('notices.notice',),
        ),
    ]
