# Generated by Django 3.1.3 on 2021-05-12 09:17

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'notices/fixture/notice_category.json', app_label='notices')

class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
