# Generated by Django 2.2.1 on 2020-07-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('credit_card', 'クレジットカード'), ('bank_transfer', '銀行振込')], max_length=120, null=True),
        ),
    ]
