# Generated by Django 2.2.1 on 2020-03-16 15:12

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_info',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
