# Generated by Django 2.2.1 on 2020-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='building',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='building',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
