# Generated by Django 2.2.1 on 2020-04-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200326_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='first_name',
            new_name='name',
        ),
    ]
