# Generated by Django 3.1.3 on 2021-04-02 16:15

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200402_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='postal_code',
            field=models.CharField(max_length=12, validators=[accounts.validators.validate_postal_code]),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='tel',
            field=models.CharField(max_length=36, validators=[accounts.validators.validate_tel]),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='postal_code',
            field=models.CharField(max_length=12, validators=[accounts.validators.validate_postal_code]),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='tel',
            field=models.CharField(max_length=36, validators=[accounts.validators.validate_tel]),
        ),
    ]
