# Generated by Django 2.2.1 on 2020-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_logorderitemstateupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_slug',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
