# Generated by Django 3.1.3 on 2023-03-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210331_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='draftprompt_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payprompt_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
