from django.urls import path
from .views import (
    OrderItemCancelAPIView,
    OrderItemReorderAPIView,
    OrderItemRetrieveAPIView,
    OrderDesignUploadAPIView,
    OrderDesignUploadCompleteAPIView,
    OrderDesignResetAPIView,
    EasyDraftInfoRetrieveAPIView,
    EasyDraftUploadAPIView,
    OrderItemReorderRetrieveAPIView,
    OrderListAPIView,
)

urlpatterns = [
    path('',
         OrderListAPIView.as_view(),
         name='order_list_api'),
    path('<str:ref_code>/',
         OrderItemRetrieveAPIView.as_view(),
         name='order_item_retrieve_api'),
    path('<str:ref_code>/cancel/',
         OrderItemCancelAPIView.as_view(),
         name='order_item_cancel_api'),
    path('<str:ref_code>/design/upload/',
         OrderDesignUploadAPIView.as_view(),
         name='order_item_design_upload_api'),
    path('<str:ref_code>/design/upload/complete/',
         OrderDesignUploadCompleteAPIView.as_view(),
         name='order_item_design_upload_complete_api'),
    path('<str:ref_code>/design/reset/',
         OrderDesignResetAPIView.as_view(),
         name='order_item_design_reset_api'),
    path('draft/<str:ref_code>/',
         EasyDraftInfoRetrieveAPIView.as_view(),
         name='easy_draft_retrieve_api'),
    path('draft/<str:ref_code>/upload/',
         EasyDraftUploadAPIView.as_view(),
         name='easy_draft_retrieve_api'),
    # TODO: いい感じのURLに変更
    path('reorder/<str:ref_code>/',
         OrderItemReorderRetrieveAPIView.as_view(),
         name='order_reorder_retrieve_api'),
    path('reorder/<str:ref_code>/add/',
         OrderItemReorderAPIView.as_view(),
         name='order_reorder_api'),
]
