from django.urls import path
from .views import (OrderHistoryView,
                    OrderHistoryItemView,
                    OrderReorderView,
                    OrderDesignUploadAPIView,
                    OrderDesignUploadRedirectView,
                    OrderDesignConfirmRedirectView,
                    OrderHistoryItemRetrieveAPIView,
                    DocumentInvoiceView,
                    DocumentReceiptView,
                    DocumentDeliveryView,)


urlpatterns = [
    path('history/',
         OrderHistoryView.as_view(),
         name='order_history'),
    path('history/<str:ref_code>/',
         OrderHistoryItemView.as_view(),
         name='order_history_item'),
    path('history/<str:ref_code>/state/',
         OrderHistoryItemRetrieveAPIView.as_view(),
         name='order_history_item_retrieve'),
    path('history/<str:ref_code>/design/upload/',
         OrderDesignUploadAPIView.as_view(),
         name='order_design_upload'),
    path('history/<str:ref_code>/design/upload/confirm/',
         OrderDesignUploadRedirectView.as_view(),
         name='order_design_upload_confirm'),
    path('history/<str:ref_code>/design/confirm/',
         OrderDesignConfirmRedirectView.as_view(),
         name='order_design_confirm'),
    path('reorder/<str:ref_code>/',
         OrderReorderView.as_view(),
         name='reorder'),
    path('documents/download/<str:ref_code>/invoice.pdf',
         DocumentInvoiceView.as_view(),
         name='document_invoice'),
    path('documents/download/<str:ref_code>/receipt.pdf',
         DocumentReceiptView.as_view(),
         name='document_receipt'),
    path('documents/download/<str:ref_code>/delivery.pdf',
         DocumentDeliveryView.as_view(),
         name='document_delivery'),
]
