# Generated by Django 3.1.3 on 2023-04-28 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudycategory',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='casestudycategory',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='説明文'),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casestudies.casestudycategory', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='overview',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='概要'),
        ),
    ]
