# Generated by Django 3.1.3 on 2023-06-06 17:20

import casestudies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0002_auto_20230428_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudycategory',
            name='advantage',
            field=models.TextField(blank=True, null=True, verbose_name='メリット'),
        ),
        migrations.AddField(
            model_name='casestudycategory',
            name='disadvantage',
            field=models.TextField(blank=True, null=True, verbose_name='デメリット'),
        ),
        migrations.AddField(
            model_name='casestudycategory',
            name='explanatory_image',
            field=models.ImageField(blank=True, null=True, upload_to=casestudies.models.get_casestudy_category_explanatory_image_path, verbose_name='アイコン'),
        ),
    ]
