# Generated by Django 3.1.3 on 2023-06-22 11:01

import casestudies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0003_auto_20230606_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='product_category',
            field=models.ManyToManyField(blank=True, related_name='product_category', to='casestudies.CaseStudyCategory', verbose_name='商品区分'),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='explanatory_image',
            field=models.ImageField(blank=True, null=True, upload_to=casestudies.models.get_casestudy_category_explanatory_image_path, verbose_name='説明画像'),
        ),
    ]
