# Generated by Django 3.1.3 on 2023-06-22 21:44

import casestudies.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0004_auto_20230622_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='image',
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=casestudies.models.get_casestudy_image_path, verbose_name='画像')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('casestudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='casestudies.casestudy')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
