# Generated by Django 3.1.3 on 2023-06-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0005_auto_20230622_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudyimage',
            name='is_hover_image',
            field=models.BooleanField(default=False),
        ),
    ]
