# Generated by Django 3.1.3 on 2023-06-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0006_casestudyimage_is_hover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='text_url',
            field=models.URLField(blank=True, null=True, verbose_name='説明文 URL'),
        ),
    ]
