# Generated by Django 3.1.3 on 2023-06-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0007_casestudy_text_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['position']},
        ),
    ]
