
name: Amazon S3

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload file to S3
        working-directory: src/static_files/static
        run: |
          # aws s3 sync ./css s3://canaldev/public/static/css --cache-control "max-age=86400"
          # aws s3 sync ./design_templates s3://canaldev/public/static/design_templates --cache-control "max-age=86400"
          # aws s3 sync ./img s3://canaldev/public/static/img --cache-control "max-age=86400"
          # aws s3 sync ./js s3://canaldev/public/static/js --cache-control "max-age=86400"
          # aws s3 sync ./webfonts s3://canaldev/public/static/webfonts --cache-control "max-age=86400"
          
          
      
